[project]
<<<<<<< HEAD
name = "erpnext"
authors = [
    { name = "Frappe Technologies Pvt Ltd", email = "developers@frappe.io"}
]
description = "Open Source ERP"
=======
name = "uiapp"
authors = [
    { name = "shravan", email = "shravanabhat.shreshta@gmail.com"}
]
description = "ui"
>>>>>>> origin/main
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
<<<<<<< HEAD
    # Core dependencies
    "pycountry~=22.3.5",
    "Unidecode~=1.3.6",
    "barcodenumber~=0.5.0",
    "rapidfuzz~=2.15.0",
    "holidays~=0.28",

    # integration dependencies
    "googlemaps",
    "plaid-python~=7.2.1",
    "python-youtube~=0.8.0",

    # Not used directly - required by PyQRCode for PNG generation
    "pypng~=0.20220715.0",
=======
    # "frappe~=15.0.0" # Installed and managed by bench.
>>>>>>> origin/main
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

<<<<<<< HEAD
[tool.black]
line-length = 99

[tool.isort]
line_length = 99
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
indent = "\t"
=======
# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"
>>>>>>> origin/main
